name: Build and Deploy Worker

on: push

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
              AUTH_KEY
              B2_APP_KEY_ID
              B2_APP_KEY
              B2_BUCKET_ID
              B2_BUCKET_NAME
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          B2_APP_KEY_ID: ${{ secrets.B2_APP_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
